apiVersion: api.adityajoshi.online/v1
kind: DeveloperEnvironment
metadata:
  labels:
    app.kubernetes.io/name: testcode
    app.kubernetes.io/instance: testcode-sample
    app.kubernetes.io/part-of: devenv-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: devenv-operator
  name: testcode
spec:
    language: nodejs
    version: "20"
    ide:
      passwordSecret: "ide-password"
      type: vscode
      extensions:
        - ms-python.python
        - golang.Go
    database:
      type: redis

