# permissions for end users to view developerenvironments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: developerenvironment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devenv-operator
    app.kubernetes.io/part-of: devenv-operator
    app.kubernetes.io/managed-by: kustomize
  name: developerenvironment-viewer-role
rules:
- apiGroups:
  - api.adityajoshi.online
  resources:
  - developerenvironments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.adityajoshi.online
  resources:
  - developerenvironments/status
  verbs:
  - get
