---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.adityajoshi.online
  resources:
  - developerenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.adityajoshi.online
  resources:
  - developerenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - api.adityajoshi.online
  resources:
  - developerenvironments/status
  verbs:
  - get
  - patch
  - update
