name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 10
          commit_message: "Updated with the latest youtube videos"
          comment_tag_name: "YOUTUBE_KUBERNETES-PLAYLIST"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          committer_email: "adityaprakashjoshi1@gmail.com"
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLuAZTZDgj0cuiFNdL0vpQoFniaA9zGcs8"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
         max_post_count: 10
         commit_message: "Updated with the latest youtube videos"
         comment_tag_name: "YOUTUBE_MONITORING-PLAYLIST"
         custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
         date_format: "mmm d, yyyy"
         template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
         committer_email: "adityaprakashjoshi1@gmail.com"
         feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLuAZTZDgj0cslJxo2yQdCIBKqDo66svpd"


